name: Release
on:
  workflow_run:
    workflows: ['Snyk Security Check', 'Tests']
    branches: [master]
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # 把分支拉出来
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      
      # 指定node版本
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      
      # 安装依赖，包括我们的 semantic-release 全套
      - name: Install dependencies
        run: npm install

      # 打包你的插件/组件/库等等等
      - name: build
        run: npm run build

      # 执行 semantic-release 发布包
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
